use db_aegtecnologia;
GO


IF OBJECT_ID('dbo.LOG_AUTOMACAO') IS NOT NULL
BEGIN
	DROP TABLE dbo.LOG_AUTOMACAO
END
GO
/****** Object:  Table [dbo].[CRED_CESTA]    Script Date: 02/05/2019 10:25:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE LOG_AUTOMACAO (
LOGID INT IDENTITY (1,1) NOT NULL,
DATACADASTRO DATETIME NOT NULL,
JOB VARCHAR (50) NOT NULL,
SUCESSO BIT NOT NULL,
MENSAGEM VARCHAR (300) NOT NULL
CONSTRAINT PK_LOG_AUTOMACAO
PRIMARY KEY (LOGID)
)