use db_aegtecnologia;
GO


IF OBJECT_ID('dbo.VEICULO_AUTOTRAC') IS NOT NULL
BEGIN
	DROP TABLE dbo.VEICULO_AUTOTRAC
END
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE VEICULO_AUTOTRAC (
VEICULOID INT NOT NULL,
DATACADASTRO DATETIME NOT NULL,
NOME VARCHAR (20) NOT NULL,
ENDERECO VARCHAR(20) NOT NULL,
CONSTRAINT PK_VEICULO_AUTOTRAC
PRIMARY KEY (VEICULOID)
)