use db_aegtecnologia;
GO


IF OBJECT_ID('dbo.VEICULO_SASCAR') IS NOT NULL
BEGIN
	DROP TABLE dbo.VEICULO_SASCAR
END
GO
/****** Object:  Table [dbo].[CRED_CESTA]    Script Date: 02/05/2019 10:25:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE VEICULO_SASCAR (
VEICULOID INT NOT NULL,
DATACADASTRO DATETIME NOT NULL,
PLACA VARCHAR (20) NOT NULL
CONSTRAINT PK_VEICULO_SASCAR
PRIMARY KEY (VEICULOID)
)