use db_aegtecnologia;
GO


IF OBJECT_ID('dbo.VEICULO_JABUR') IS NOT NULL
BEGIN
	DROP TABLE dbo.VEICULO_JABUR
END
GO
/****** Object:  Table [dbo].[CRED_CESTA]    Script Date: 02/05/2019 10:25:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE VEICULO_JABUR (
VEICULOID INT NOT NULL,
DATACADASTRO DATETIME NOT NULL,
PLACA VARCHAR (7) NOT NULL,
ESPELHADOATE DATETIME NOT NULL
CONSTRAINT PK_VEICULO_JABUR
PRIMARY KEY (VEICULOID)
)