USE [MovimentosManuais]
GO

/****** Object:  Table [dbo].[MOVIMENTO_MANUAL]    Script Date: 9/21/2019 10:55:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOVIMENTO_MANUAL](
	[DAT_MES] [int] NOT NULL,
	[DAT_ANO] [int] NOT NULL,
	[NUM_LANCAMENTO] [int] NOT NULL,
	[COD_PRODUTO] [char](4) NOT NULL,
	[COD_COSIF] [char](11) NOT NULL,
	[VAL_VALOR] [numeric](18, 2) NULL,
	[DES_DESCRICAO] [varchar](max) NULL,
	[DAT_MOVIMENTO] [smalldatetime] NULL,
	[COD_USUARIO] [varchar](100) NULL,
 CONSTRAINT [chave_composta] PRIMARY KEY CLUSTERED 
(
	[COD_PRODUTO] ASC,
	[COD_COSIF] ASC,
	[DAT_MES] ASC,
	[DAT_ANO] ASC,
	[NUM_LANCAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOVIMENTO_MANUAL]  WITH CHECK ADD FOREIGN KEY([COD_PRODUTO])
REFERENCES [dbo].[PRODUTO] ([COD_PRODUTO])
GO


